version: '3.8'

services:
  # MySQL Database Service
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=htr_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - htr-network

  # Redis Service for Celery
  redis:
    image: redis:7-alpine
    networks:
      - htr-network

  # Flask Web Application Service
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - htr-network
    command: >
      sh -c "flask db upgrade &&
             gunicorn --bind 0.0.0.0:5000 run:app"

  # Celery Worker Service
  worker:
    build: .
    command: celery -A app.tasks.celery worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db
    networks:
      - htr-network

networks:
  htr-network:
    driver: bridge

volumes:
  mysql_data:
