services:
  htr-flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=false
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
      - ./data:/app/data
      - ./htr_pipeline:/app/htr_pipeline
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - htr-network

networks:
  htr-network:
    driver: bridge

volumes:
  uploads:
  results:
  logs: